# Generated by Django 2.1.5 on 2019-04-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
