# Generated by Django 2.1.5 on 2019-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esop', '0002_remove_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
